name = "companion"
description = "Safe Language Annotated SPARK Companion"
version = "0.1.0"
authors = ["Safe Companion Team"]
maintainers = ["Safe Companion Team <safe@example.com>"]
maintainers-logins = ["berkeleynerd"]

[[depends-on]]
gnat = "*"
gprbuild = "*"
